[package]
name = "htwmensa"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "htwmensa"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clokwerk= "0.4.0"
serde = {version="1.0.152", features = ["derive"]}
reqwest = {version="0.11.13", features = ["blocking", "json", "async-compression", "rustls"]}
chrono = {version = "0.4.23", features= ["serde"]}
tokio = {version = "1.13.0", features = ["full"]}
postgres = {version = "0.19.4", features = ["with-chrono-0_4"]}
teloxide = { version = "0.11.3", features = ["macros", "rustls"] }
env_logger = "0.10.0"
log = "0.4.17"