[package]
name = "HTWMensa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clokwerk= "0.4.0"
serde = {version="1.0.152", features = ["derive"]}
reqwest = {version="0.11.13", features = ["blocking", "json", "async-compression"]}
chrono = {version = "0.4.23", features= ["serde"]}
tokio = {version = "1.13.0", features = ["full"]}