FROM talk.schwanzer.online/dockerhub_proxy/library/rust:bullseye as dependency-cache
USER root

RUN apk add pkgconfig openssl-dev libc-dev
WORKDIR /app/src

ADD Cargo.toml .
ADD dummy.rs ./src/main.rs
RUN RUSTFLAGS='-C target-feature=-crt-static' cargo build --release


FROM talk.schwanzer.online/dockerhub_proxy/library/rust:bullseye as builder

COPY --from=dependency-cache /usr/local/cargo /usr/local/cargo
COPY --from=dependency-cache /app/src/target/ /app/src/target/
RUN rm -rf /app/src/target/release/deps/htwmensa*
RUN rm -rf /app/src/target/release/htwmensa*

WORKDIR /app/src
RUN USER=root

COPY ./ ./
RUN cargo build --release



FROM talk.schwanzer.online/dockerhub_proxy/library/debian:stable-slim
WORKDIR /app
RUN apt update \
    && apt install -y openssl ca-certificates \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \


EXPOSE 80 443

COPY --from=builder /app/src/target/release/htwmensa /app/htwmensa

CMD ["/app/htwmensa"]